### ISSUE TITLE
Input length

### ISSUE THREAD

**Issue by becvert** [shriprem/Goto-Line-Col-NPP-Plugin#1]
Hello.
I have a file with a line of 379347 characters.
But I cannot type in more than 5 numbers in the At Column field.
Please advise
Thank you

**Comment by shriprem** [comment]
I have increased the Goto Line/Column intake from 5 digits to 8 digits per your request.

I have also tested with a file having column positions of around 350,000 characters.

Please manually download the [v1.0.0.1](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v1.0.0.1) zipped binary (x86/x64) to match your NPP. Copy it to the `<NPP_Plugins_folder>/GotoLineCol subdirectory` to overwrite the existing DLL. Let me know if I can close this issue.

**Comment by becvert** [comment]
It works!
Well done. Very reactive. I love it :thumbsup:
