### ISSUE TITLE
[Feature Request] Add base conversions of text at caret

### ISSUE THREAD

**Issue by alankilborn** [shriprem/Goto-Line-Col-NPP-Plugin#31]
Continuing conversation from [HERE](https://community.notepad-plus-plus.org/post/77640).

Since this plugin seems to do a bit more than go-to-line-and-column, I thought perhaps it could do even more with the empty space on its panel:

![image](https://user-images.githubusercontent.com/77065706/174477934-1fdc33d5-1f97-412b-b25f-74cf9a5a0ff3.png)

I often have a need to see a decimal value that is textually represented in my files, as hex.  For me this means I need to fire up Windows calculator, make sure it is in the correct mode and on the correct base, and they type in (or copy in) my number and then select the new base.  Then, if I need to do something with the hex equivalent, I have to copy it and "take it back" to Notepad++.

My idea for the plugin is to add conversion of the "number" at the caret to different base, and to allow copy of the converted result.  Decimal and hex meets my need, but binary could be handy as well.  Another nicety would be negative numbers but that adds a complication about bit length (are the numbers 32-bit, 64-bit, other?).

There is some ambiguity, e.g. `1234` at the caret could be decimal or hex.  The suggestion here would be to consider and covert it both ways, i.e, present `1234 = 0x4D2` and `0x1234 = 4660`.  Of course, if the number already has a prefix of `0x` or `$` it could be presented without guesswork as `0x1234 = 4660`.  A prefix for binary is reasonable as `0b` as in, e.g. Python.

If binary is to be supported, it might be nice to have some spacing in the visual (but not the copyable) output, as when too many bits are strung together, it is easy to lose your place.  Maybe separate on an 8-bit basis, e.g. `14179914 = 0b 11011000 01011110 01001010` or perhaps 4-bit basis as Windows calculator does it.

As for copying results, a button to the right of presented output might be the way to go, like these in yellow:

![image](https://user-images.githubusercontent.com/77065706/174477896-2819a2fa-1cd5-41e3-b76f-c8a014d8845f.png)

**Comment by shriprem** [comment]
@alankilborn , thank you for your detailed requirements. It clarifies a lot of things.

But when you say:
> Of course, if the number already has a prefix of `0x` or `$` it could be presented without guesswork...

Do you mean that the `$` is the currency indicator and therefore is an amount in decimal?

P.S: As I had mentioned earlier in the NPP BB, it might be a few weeks before I can get started on this enhancement since I have a couple of other projects that I am working on right now.
